version: "3"

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    container_name: mysqldb
    build:
      context: ./mysql
      dockerfile: ./mysql.Dockerfile
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - "./data/db:/var/lib/mysql"
      # - db:/var/lib/mysql
  # app:
  #   depends_on:
  #     - mysqldb
  #   build: 
  #     context: ./app
  #     dockerfile: ./Dockerfile
  #   env_file: ./.env
  #   ports:
  #     - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
  #   environment:
  #     - DB_HOST=mysqldb
  #     - DB_USER=$MYSQLDB_USER
  #     - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
  #     - DB_NAME=$MYSQLDB_DATABASE
  #     - DB_PORT=$MYSQLDB_DOCKER_PORT
  #   stdin_open: true
  #   tty: true

